import Link from "next/link";
import Header from "../components/Header";

const lastUpdated = "July 2026";
const legalLinks = [["Terms", "/terms"], ["Privacy", "/privacy"], ["Buyer Protection", "/buyer-protection"], ["Seller Rules", "/seller-rules"], ["Fees", "/fees"], ["Shipping", "/shipping-policy"], ["Refunds & Disputes", "/refund-dispute-policy"], ["Prohibited Items", "/prohibited-items"]];
const sections = [
  { title: "Not Allowed", body: ["Counterfeit or fake cards, stolen items, illegal items, and items that violate law are not allowed on GRAIL.", "Misrepresented grades, cert numbers, condition, serial numbers, or card identity are not allowed."] },
  { title: "Disclosure Required", body: ["Altered, trimmed, restored, damaged, recolored, or otherwise modified cards must be clearly disclosed if allowed at all.", "Resealed packs or boxes are prohibited unless specifically allowed and clearly disclosed under future product rules."] },
  { title: "Unsafe Or Offensive Material", body: ["Offensive, illegal, hateful, exploitative, or otherwise unsafe material may be removed at GRAIL's discretion."] },
  { title: "Marketplace Discretion", body: ["GRAIL may remove any listing, hold payout, limit account access, or request additional review when an item creates authenticity, safety, fraud, legal, or marketplace risk."] },
];

export default function ProhibitedItemsPage() { return <PolicyPage eyebrow="Prohibited Items" title="Prohibited Items" sections={sections} />; }
function PolicyPage({ eyebrow, title, sections }: { eyebrow: string; title: string; sections: { title: string; body: string[] }[] }) { return <main className="policy-page"><style>{pageStyles}</style><div className="policy-shell"><Header /><section className="policy-heading"><span>{eyebrow}</span><h1>{title}</h1><p>Items and listing behavior not allowed on GRAIL.</p><strong>Last updated: {lastUpdated}</strong></section><section className="policy-card">{sections.map((section) => <article key={section.title}><h2>{section.title}</h2>{section.body.map((item) => <p key={item}>{item}</p>)}</article>)}</section><LegalNav /></div></main>; }
function LegalNav() { return <section className="legal-nav">{legalLinks.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</section>; }
const pageStyles = `.policy-page{min-height:100vh;background:radial-gradient(circle at 50% -120px,rgba(201,205,211,.08),transparent 32%),linear-gradient(180deg,#000 0%,#030304 58%,#000 100%);color:#fafafa;font-family:Arial,Helvetica,sans-serif}.policy-shell{width:min(980px,calc(100vw - 32px));margin:0 auto;padding:8px 0 42px}.policy-heading{margin-top:24px}.policy-heading span{color:#C9CDD3;font-size:11px;line-height:14px;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.policy-heading h1{margin:8px 0 0;color:#fff;font-size:42px;line-height:46px;font-weight:900}.policy-heading p,.policy-card p{color:#a1a1aa;font-size:14px;line-height:22px;font-weight:700}.policy-heading strong{display:inline-flex;margin-top:10px;color:#E7DED0;font-size:12px;font-weight:900}.policy-card{margin-top:18px;border:1px solid #1d1d22;border-radius:12px;background:linear-gradient(180deg,rgba(255,255,255,.035),rgba(255,255,255,.006)),rgba(5,5,6,.92);box-shadow:0 18px 44px rgba(0,0,0,.28);padding:18px;display:grid;gap:18px}.policy-card article{border-bottom:1px solid rgba(201,205,211,.1);padding-bottom:16px}.policy-card article:last-child{border-bottom:0;padding-bottom:0}.policy-card h2{margin:0;color:#fff;font-size:20px;line-height:24px;font-weight:900}.legal-nav{margin-top:18px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.legal-nav a{border:1px solid rgba(231,222,208,.22);border-radius:10px;background:rgba(231,222,208,.055);color:#fff;min-height:42px;display:inline-flex;align-items:center;justify-content:center;text-decoration:none;font-size:12px;font-weight:900;text-align:center}.legal-nav a:hover{border-color:rgba(231,222,208,.58);background:rgba(231,222,208,.1)}@media(max-width:760px){.legal-nav{grid-template-columns:repeat(2,minmax(0,1fr))}.policy-heading h1{font-size:34px;line-height:38px}}`;
